Update requires-python (#5)
It doesn't actually run in 3.7

```bash
$ python3.8 alidistlint >/dev/null root.sh                                            0.19s
Traceback (most recent call last):
  File "/Users/sergio/.cache/uv/archive-v0/v7fTvvh4DiydfFItL7P4S/bin/alidistlint", line 6, in <module>
    from alidistlint.run import main
  File "/Users/sergio/.cache/uv/archive-v0/v7fTvvh4DiydfFItL7P4S/lib/python3.8/site-packages/alidistlint/run.py", line 11, in <module>
    from alidistlint.headerlint import headerlint
  File "/Users/sergio/.cache/uv/archive-v0/v7fTvvh4DiydfFItL7P4S/lib/python3.8/site-packages/alidistlint/headerlint.py", line 12, in <module>
    ValidationErrors = list[Union[str, dict[Any, 'ValidationErrors']]]
TypeError: 'type' object is not subscriptabl
```